kind: pipeline
type: docker
name: default

steps:
  # Step untuk testing (opsional)
  - name: test
    image: node:16
    commands:
      - npm install
      - npm test
    when:
      event:
        - push
        - pull_request

  # Step untuk build
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: mahendra968/drone-demo
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
      build_args:
        - NODE_ENV=production
      dockerfile: Dockerfile
      context: .
    when:
      branch:
        - main
      event:
        - push

  # Step untuk deploy
  - name: deploy
    image: appleboy/drone-ssh
    depends_on:
      - build
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      key:
        from_secret: ssh_key
      port: 22
      script:
        - docker pull mahendra968/drone-demo:latest
        - docker stop drone-demo || true
        - docker rm drone-demo || true
        - >
          docker run -d --name drone-demo 
          --restart unless-stopped 
          -p 3000:3000 
          -e NODE_ENV=production 
          --network app-network 
          mahendra968/drone-demo:${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - main
      event:
        - push

# Tambahkan volume jika diperlukan
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
