kind: pipeline
name: default

steps:
  - name: build
    image: docker:20.10.7
    privileged: true
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: mahendra968/drone-demo
      tags:
        - latest
    when:
      branch:
        - main

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      key:
        from_secret: ssh_key
      port: 22
      script:
        - docker pull mahendra968/drone-demo:latest
        - docker stop drone-demo || true
        - docker rm drone-demo || true
        - docker run -d --name drone-demo -p 3000:3000 mahendra968/drone-demo:latest
    when:
      branch:
        - main
